<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lost Item Report - {{ $item->title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            font-size: 24px;
            font-weight: bold;
            color: #2d3748;
        }
        .section {
            margin-bottom: 20px;
        }
        .section h2 {
            font-size: 18px;
            font-weight: bold;
            color: #4a5568;
            margin-bottom: 10px;
        }
        .section p {
            font-size: 14px;
            color: #4a5568;
            text-align: justify;
        }
        .qr-code {
            text-align: center;
            margin: 20px 0;
        }
        .barcode {
            text-align: center;
            margin: 20px 0;
        }
        .images {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
            margin-bottom: 20px;
        }
        .images img {
            width: 200px;
            height: auto;
            border-radius: 8px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 12px;
            color: #718096;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>Lost Item Report</h1>
        <p>Generated by <strong>Lost & Found System</strong></p>
    </div>



    <!-- Item Details -->
    <div class="section">
        <h2>Item Title</h2>
        <p>{{ $item->title }}</p>
    </div>

    <!-- Description -->
    <div class="section">
        <h2>About the Item</h2>
        <p>
            This item, <strong>{{ $item->title }}</strong>, was last seen at <strong>{{ $item->location }}</strong> on <strong>{{ $item->date_lost->format('F j, Y') }}</strong>. The owner is hopeful for its safe return.
        </p>
        <p>
            It is in <strong>{{ $item->condition }}</strong> condition and has unique features for identification. Please contact the owner if found.
        </p>
    </div>

    <!-- Images -->
    @if ($item->images->isNotEmpty())
        <div class="section">

            <div class="images">
                @foreach ($item->images as $image)
                    <img src="{{ storage_path('app/public/' . $image->image_path) }}" alt="{{ $item->title }}" style="width: 200px;">
                @endforeach
            </div>
        </div>
    @endif

    <!-- Reported By -->
    <div class="section">
        <h2>Reported By</h2>
        <p>
            @if ($item->is_anonymous)
                The reporter has chosen to remain anonymous.
            @else
                Reported by <strong>{{ $item->user->name }}</strong>.
            @endif
        </p>
    </div>


    <!-- Footer -->
    <div class="footer">
        <p>Generated on {{ now()->format('F j, Y') }} by Lost & Found System</p>
    </div>
</body>
</html>
