services:
  laravel:
    restart: unless-stopped
    container_name: laravelapp
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    volumes:
      - ../storage/app:/var/www/html/storage/app
    environment:
      - APP_NAME=LostFoundApp
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:RfsWisbwKMmFQ+0SP/E8ZuiaAyoSNe7xm6JG4BZb328=
      - APP_VERSION=1.0
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=lost_found_hub
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password
      - MAIL_MAILER=smtp
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=null
      - MAIL_FROM_NAME=LostFoundApp
      - HUGGING_FACE_API_KEY=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 # Add Hugging Face API key
    ports:
      - "8080:80"
    networks:
      - laravel-network
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lost_found_hub
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - v-database:/var/lib/mysql
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_password
    ports:
      - "8081:80"
    networks:
      - laravel-network

volumes:
  v-database:

networks:
  laravel-network:
    driver: bridge
